name: Actualizar CSV carburantes

on:
  schedule:
  # Invierno (UTC+1)
  - cron: "0 7 * 11-12,1-3 *"

  # Verano (UTC+2)
  - cron: "0 6 * 4-10 *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Commit CSV actualizado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add gasolina.csv
          git commit -m "Actualización diaria CSV" || echo "Sin cambios"
          git push
